### ISSUE TITLE
[feat] gallery page/link for TezosPride event

### ISSUE THREAD

**Issue by AliaK77** [teia-community/teia-ui#103]
**Is your feature request related to a problem? Please describe.**
Could we please have a gallery/event page/link for Tezos Pride event, similar to the Ukraine Fundraiser link (which was PR45 https://github.com/teia-community/teia-ui/pull/45 for reference)

This event may need to use the event tag instead of contract id like UA fundraiser query did 

Mal has mentioned NFTBiker had an option to add list of work to a spreadsheet and have those included in the event page, eg for those who forget to use the event tag

**Describe the solution you'd like**
A link for the Tezos Pride event on Teia homepage that links to a page showing the artwork tagged with event tag, similar to the Ukraine link
<img width="212" alt="image" src="https://user-images.githubusercontent.com/4126913/172596736-287be4ac-1116-4ac4-bf82-53b81d19aa5e.png">

**Describe alternatives you've considered**
The alternative is to use the gallery feature and manually update JSON file, though this is not a dynamic list of work, it would need manual operations. This would cater for any not using the event tag. for this case, there'd be a new gallery in the Gallery page rather than a link on homepage (so different to UA fundraiser event)

Please advise if this is preferred option over the dynamic link above

**Additional context**
please contact MaliciousSheep or AliaK in discord

initial discussion for this request: https://discord.com/channels/908672304236625970/951351576839221248/982983061610319944

discord link for TezosPride event planning: https://discord.com/channels/908672304236625970/981374833642328084

**Comment by melMass** [comment]
I'm looking into this. 
Filtering the tag is very trivial, the only thing would be to sync with what you prepared with @nftbiker for the "extra" objkts that were not properly taggued?

I will open a PR now for the tag

**Comment by AliaK77** [comment]
MaliciousSheep mentioned Biker used to setup a spreadsheet which Mal would fill in if someone hadn't set the tag - see https://discord.com/channels/908672304236625970/951351576839221248/983008095548624966
if this isn't possible, we could suggest artists to burn and remint with the tag to be included in the event page/listing?
thanks very much

**Comment by AliaK77** [comment]
thanks very much
