### ISSUE TITLE
[bug] cannot Sync Wallet 

### ISSUE THREAD

**Issue by muhAzri** [teia-community/teia-ui#111]
Cannot Sync a wallet either on pc or phone 

And when im try to sync if I look in the console it shows this error:

```ruby
main.ca416e67.js:1 Uncaught (in promise) Error: libsodium was not correctly initialized.
    at r (main.ca416e67.js:1:26808)
    at main.ca416e67.js:1:41561
```

**Comment by melMass** [comment]
Thanks for reporting it, something went south in our last deployment, pinging @jmagly

**Comment by merchantcoppola** [comment]
should be solved now

**Comment by melMass** [comment]
The issue was found and solved! 
Thanks for the report
