### ISSUE TITLE
[support] metaData not loading

### ISSUE THREAD

**Issue by JNK101** [teia-community/teia-ui#112]
Objkt minted on TEIA 7 hours ago. Metadata are still described as being queued. 

https://teia.art/khc
tz1V6f3bXuZV6Qu8MPJHZgdHkt4w1UVuEqrG
OBJKT#747226

![SC1](https://user-images.githubusercontent.com/107600466/173988294-2649e92b-7cb6-47cb-9ace-a2dd536572f4.png)

![SC2](https://user-images.githubusercontent.com/107600466/173988304-be294d81-e653-45cb-89b0-3b50582a23d4.png)

**Comment by Zir0h** [comment]
Yeah this happens a lot. As a workaround I restart the indexer.
Metadata is there now.

**Comment by melMass** [comment]
Another option that usually "refreshes" it is to swap it

**Comment by Zir0h** [comment]
Indeed in [on_swap](https://github.com/teia-community/hicdex/blob/main/src/hicdex/handlers/on_swap_v2.py#L40) the fix_metadata function is called again. And by then the metadata has had the chance to propagate in the ipfs network.

**Comment by melMass** [comment]
> Indeed in [on_swap](https://github.com/teia-community/hicdex/blob/main/src/hicdex/handlers/on_swap_v2.py#L40) the fix_metadata function is called again. And by then the metadata has had the chan

Good to know I did not know those details ❤️ .

@JNK101 I'm closing it, feel free to re-open or re-create a separate issue if it happens again.

**Comment by JNK101** [comment]
Thank you very much !!
