### ISSUE TITLE
[feat] update Teia indexer to support new metadata fields

### ISSUE THREAD

**Issue by LeonNicholls** [teia-community/teia-ui#114]
The Teia marketplace minter logic is being updated to support new metadata fields based on this requirements doc: https://docs.google.com/document/d/1R3rxuJfpCBoh52wDsYpEmY_iuH8sd6l17oh4nk7jlRE/edit?usp=sharing

See: https://github.com/teia-community/teia-ui/pull/104 and https://github.com/teia-community/teia-ui/pull/113

The Teia indexer needs to be updated to make the new metadata available via the GraphQL API so it can be displayed in the Teia marketplace UI for mints.

Example of new metadata: https://teia.rocks/objkt/748200

**Comment by Zir0h** [comment]
I installed the [dipdup metadata indexer](https://github.com/dipdup-net/metadata) at https://api-metadata.teia.rocks/v1/graphql
Would that be enough to add the new fields to the UI?

``` json 
{
  "data": {
    "token_metadata": [
      {
        "metadata": {
          "date": "2022-06-17T19:52:35.249Z",
          "name": "Testing new fields",
          "tags": [
            "test"
          ],
          "rights": "cc-by-nc-nd-4.0",
          "symbol": "OBJKT",
          "formats": [
            {
              "uri": "ipfs://QmR4HHarGZkYRu3vWxXAYjGQgb8eNQEZgQJ28wAVfLGuKM",
              "fileName": "tz1and_screenshot (28).png",
              "fileSize": 991884,
              "mimeType": "image/png",
              "dimensions": {
                "unit": "px",
                "value": "3072x1628"
              }
            },
            {
              "uri": "ipfs://QmUxFzPJ647NHWWzNNLWxn3S731CUfWttoHCWwxcn5Yw2D",
              "fileName": "cover_tz1and_screenshot (28).png",
              "fileSize": 263028,
              "mimeType": "image/png",
              "dimensions": {
                "unit": "px",
                "value": "1024x542"
              }
            },
            {
              "uri": "ipfs://QmZ8inAx1SgZrgJaVEUJNkYBCRPXGYNeV8utuqvV1ndCr5",
              "fileName": "thumbnail_tz1and_screenshot (28).png",
              "fileSize": 45690,
              "mimeType": "image/png",
              "dimensions": {
                "unit": "px",
                "value": "350x185"
              }
            }
          ],
          "creators": [
            "tz1XtjZTzEM6EQ3TnUPUQviCD6WfcsZRHXbj"
          ],
          "decimals": 0,
          "language": "cs",
          "rightUri": "",
          "attributes": [
            {
              "name": "nsfw",
              "type": "boolean",
              "value": true
            },
            {
              "name": "photosensitiveSeizureWarning",
              "type": "boolean",
              "value": false
            }
          ],
          "displayUri": "ipfs://QmUxFzPJ647NHWWzNNLWxn3S731CUfWttoHCWwxcn5Yw2D",
          "artifactUri": "ipfs://QmR4HHarGZkYRu3vWxXAYjGQgb8eNQEZgQJ28wAVfLGuKM",
          "description": "testing",
          "thumbnailUri": "ipfs://QmZ8inAx1SgZrgJaVEUJNkYBCRPXGYNeV8utuqvV1ndCr5",
          "isBooleanAmount": false,
          "shouldPreferSymbol": false
        }
      }
    ]
  }
}
```

**Comment by LeonNicholls** [comment]
It's not clear to me how we would query based on the attribute values. For example, if we wanted all OBJKTs that don't have the NSFW attribute enabled. Or the opposite, get a list of OBJKTs that have the NSFW attribute enabled.

The requirements for the GUI haven't all been determined yet, but this doc has some ideas: https://docs.google.com/document/d/1-lVHayB9unVHfLqPt19BjfVdGJ8hPRUAD1XOQSpwEQc/edit?usp=sharing

**Comment by melMass** [comment]
Nice, I'm indeed not sure we can't filter them out in graphql only with this setup.

Not sure what is happening @Zir0h but it seems like there is an offset?

The following (the test token I minted):

```graphql
query MyQuery {
  token_metadata(where: {id: {_eq: "747811"}}) {
    metadata
  }
}
```

Returns:

```json
{
  "data": {
    "token_metadata": [
      {
        "metadata": {
          "name": "Comfortable Isolation",
          "tags": [
            "photography",
            "normalityistoxic",
            "nature",
            "digitalphotography",
            "1/1"
          ],
          "symbol": "OBJKT",
          "formats": [
            {
              "uri": "ipfs://QmU12nx6V3kA4AUysBoRyrf1qy8DBjG9Lv9p1vochPtLL3",
              "mimeType": "image/png"
            }
          ],
          "creators": [
            "tz1gADRowRshmxVnXgLRBWU9aH2gvDKc2tLC"
          ],
          "decimals": 0,
          "displayUri": "ipfs://QmPhCLWVNbyCFsbAumCK3Z1bSrEMMmR9gzVvtfE5yr4uCg",
          "artifactUri": "ipfs://QmU12nx6V3kA4AUysBoRyrf1qy8DBjG9Lv9p1vochPtLL3",
          "description": "In the PNW there are many pockets and hidden gems of nature that are under-appreciated. Near my town of Bellingham minutes from where I live there is a waterfall park called Whatcom Falls where you can see rapid waters and beautiful scenery. There's no place else like this one and I am very lucky and fortunate to live where I can escape so easily and enjoy total isolation from the city, from people, from stress and still not be too far away. It's the little things we need to hold on to. The little things we need to appreciate.  ",
          "thumbnailUri": "ipfs://QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc",
          "isBooleanAmount": false,
          "shouldPreferSymbol": false
        }
      }
    ]
  }
}
```

Which corresponds to https://teia.art/objkt/747948 and not https://teia.art/objkt/747811

**Comment by Zir0h** [comment]
Yes, you have to use token_id (and maybe contract too, but for now only KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton is indexed).
```
query MyQuery {
  token_metadata(where: {token_id: {_eq: "748200"}}) {
    metadata
  }
}
```

I'll adapt the current token table to add the metadata there, then we'll be able to use it as a filter I think. (I have no idea what I'm doing to this is a bit of trial&error I"m afraid)

**Comment by melMass** [comment]
> Yes, you have to use token_id 

Ahhh rookie mistake, thanks, what is ID referring to?
I think @xat might have some input regarding better graphql accessibility of those attributes

**Comment by Zir0h** [comment]
> 
> Ahhh rookie mistake, thanks, what is ID referring to? 

Just some internal id I think, it's the same way on https://dipdup.net/sandbox.html?service=metadata

**Comment by xat** [comment]
i agree that it's probably best to store the additional metadata in the token-table.

basically, this model needs to be extended with further fields:

https://github.com/teia-community/hicdex/blob/main/src/hicdex/models.py#L48-L67

afterward these fields can be filled with data in the `fix_token_metadata` function:

https://github.com/teia-community/hicdex/blob/main/src/hicdex/metadata_utils.py#L27-L38

**Comment by Zir0h** [comment]
Thank you for your patience and guidance people! I've updated the code with the new fields and am now re-indexing the metadata locally.

**Comment by Zir0h** [comment]
Now it's like this:

``` json
{
  "data": {
    "token": [
      {
        "artifact_uri": "ipfs://QmR4HHarGZkYRu3vWxXAYjGQgb8eNQEZgQJ28wAVfLGuKM",
        "attributes": [
          {
            "name": "nsfw",
            "type": "boolean",
            "value": true
          },
          {
            "name": "photosensitiveSeizureWarning",
            "type": "boolean",
            "value": false
          }
        ],
        "formats": [
          {
            "uri": "ipfs://QmR4HHarGZkYRu3vWxXAYjGQgb8eNQEZgQJ28wAVfLGuKM",
            "fileName": "tz1and_screenshot (28).png",
            "fileSize": 991884,
            "mimeType": "image/png",
            "dimensions": {
              "unit": "px",
              "value": "3072x1628"
            }
          },
          {
            "uri": "ipfs://QmUxFzPJ647NHWWzNNLWxn3S731CUfWttoHCWwxcn5Yw2D",
            "fileName": "cover_tz1and_screenshot (28).png",
            "fileSize": 263028,
            "mimeType": "image/png",
            "dimensions": {
              "unit": "px",
              "value": "1024x542"
            }
          },
          {
            "uri": "ipfs://QmZ8inAx1SgZrgJaVEUJNkYBCRPXGYNeV8utuqvV1ndCr5",
            "fileName": "thumbnail_tz1and_screenshot (28).png",
            "fileSize": 45690,
            "mimeType": "image/png",
            "dimensions": {
              "unit": "px",
              "value": "350x185"
            }
          }
        ],
        "title": "Testing new fields",
        "timestamp": "2022-06-17T19:52:59+00:00",
        "rights_uri": null,
        "rights": "cc-by-nc-nd-4.0"
      }
    ]
  }
}
```

And this seems to work (although it does seem a bit "verbose" to search on an attribute):
![2022-07-04-220749_1754x749_scrot](https://user-images.githubusercontent.com/546070/177212142-ed564cf5-be64-4669-b521-d6e4ebe8444e.png)

I'll re-install the testing api tomorrow (I managed to break it with my testing :sweat_smile: )

**Comment by Zir0h** [comment]
https://api-testing.teia.rocks/v1/graphql up&running with the code from https://github.com/Zir0h/hicdex/commit/e780579fba7acd2c957e94bfe437057f6b01ebe7

**Comment by LeonNicholls** [comment]
Cool. Is it possible to also map the attributes to the same level as the other metadata fields like artifactUri to simplify the query?

**Comment by Zir0h** [comment]
The artifact_uri is a single string value, where as the attributes fields can contain many different values.
Maybe I understood wrong. Will the attributes be a defined/hard coded list? Like now there are photosensitiveSeizureWarning and nsfw. If that's the case, then yes, I can remove the attributes field and replace it with 2 boolean fields (nsfw / photosensitiveSeizureWarning) in the token model.
Right now I've left it a jsonb "attributes" field so that new attributes can be added in the future without needing a model change.

**Comment by LeonNicholls** [comment]
Since the indexer is customized for Teia's needs anyhow, I don't think it's necessarily a bad thing to do something like this for these new attributes. Being able to simply ask like " token where nsfw = true" would be a much simpler query syntax. I understand that this will require an indexer update for new attributes, but I don't expect new attributes to be added on a frequent basis.

Anyhow, these are just my initial thoughts; it would be good to hear from the other devs. I buy the argument that keeping the attributes JSON structure for query filtering is more future-proof and less maintenance.

**Comment by melMass** [comment]
I'm not too sure is there a graphQL way to filter json like structure attributes? I feel like this would be more flexible indeed instead of hard coding each keys at the top level

**Comment by Zir0h** [comment]
> I'm not too sure is there a graphQL way to filter json like structure attributes? I feel like this would be more flexible indeed instead of hard coding each keys at the top level

This works in graphql:
```
query MyQuery($attributes: jsonb) {
  token(where: {attributes: {_contains: $attributes}}) {
    id
    title
    attributes
    artifact_uri
  }
}
```
with variables:
``` json
{
  "attributes": [{
    "name": "nsfw", "type": "boolean", "value": true
  }]
}
```

It gets the red error underlining, but it seems to work anyway.

**Comment by melMass** [comment]
But I meant can we use "where attributes -eq "nsfw" where value -eq true" for instance

**Comment by Zir0h** [comment]
> But I meant can we use "where attributes -eq "nsfw" where value -eq true" for instance

[Not yet](https://github.com/hasura/graphql-engine/issues/2468) I'm afraid.

**Comment by LeonNicholls** [comment]
Ok. Technically it works as a solution. I'm wondering if we should come up with some possible queries to ensure we have what we need. 

I'm assuming that we might want to remove NSFW from the feeds if the user wants that, then we might need a query like this:
```
query MyQuery($attributes: jsonb) {
  token(where: {_or: [{attributes: {_contains: $attributes}}, {attributes: {_is_null: true}}]}, order_by: {id: desc}) {
    id
    title
    attributes
    artifact_uri
  }
}
```
```
{"attributes": [{
    "name": "nsfw",
    "type": "boolean",
    "value": false
  }]}
```

But I don't think I got this right, since the results don't show all the latest mints. I'm trying to filter for OBJKTs that either has the NSFW flag set to false or don't have the attributes at all.

**Comment by Zir0h** [comment]
Your query seems to work fine to me? (attention, api limit is 10000 results without the admin token)

**Comment by LeonNicholls** [comment]
Only if I don't have the attribute conditions, then I'm getting the latest mints in the results:
```
query MyQuery {
  token(order_by: {id: desc}) {
    id
    title
    attributes
    artifact_uri
  }
}
```

**Comment by Zir0h** [comment]
Ooh I see, that's because the default value is {} and not NULL.
There are some null's in there too, because I was lazy. I've fixed the data.

So the query should probably be something like this (without the id restrictions):
```
query MyQuery($attributes: jsonb) {
  token(
    where: {
      _and: {
        _or: [
          {attributes: {_contains: $attributes}}, 
          {attributes: {_contains: {}}}
        ], 
        _and: {
          id: {_gte: "754300", _lte: "754400"}
        }
      }
    }, order_by: {id: desc}) {
    id
    title
    attributes
    artifact_uri
  }
}
```

``` json
{"attributes": [{
    "name": "nsfw",
    "type": "boolean",
    "value": false
  }]}
```

I can also switch the default value to null, but I don't know what would be the easiest to manage on the frontend.

**Comment by LeonNicholls** [comment]
Ah. Ok. Not sure I have a preference between null or {}. Don't think it makes much of a difference for the GUI code.

**Comment by melMass** [comment]
Solved in: https://github.com/Zir0h/hicdex/commit/e780579fba7acd2c957e94bfe437057f6b01ebe7

Don't hesitate to reopen if needed!

**Comment by Zir0h** [comment]
I haven't merged that yet :smile: 
So it's good to go? I can still change it to 2 separate boolean fields instead of the one jsonb field, and NULL values instead of empty object?

**Comment by melMass** [comment]
My bad @Zir0h I thought this was solved, let's maybe wait for more inputs you're right :)

**Comment by Zir0h** [comment]
So, can I go ahead with this? :smile:

**Comment by LeonNicholls** [comment]
I'm assuming this is still needed as a backup for the Teztok effort.

**Comment by Zir0h** [comment]
This is now running in prod, I was tired of constantly fixing the "metadata on queue" stuff :sweat_smile:

**Comment by melMass** [comment]
Ok closing it now 😆 !
We could always reference it later on in a new issue.
