### ISSUE TITLE
[bug] lowest price still collectable from banned accounts

### ISSUE THREAD

**Issue by spacegoodies** [teia-community/teia-ui#116]
**Summary**
As a collector, I am still allowed to collect from banned accounts using the HENv2 contract when the swapped price is the lowest price.

**Description**
Example
- https://teia.art/objkt/45586
- Banned account is https://teia.art/hen
- Banned account listing is 0.15 and is still shown on the main collect button, but is restricted on the "Listings" tab
- Any objkt listed as the lowest price by a banned account can still be collected by users.

**Screenshots**
<img width="732" alt="Screen Shot 2022-06-24 at 8 31 44 AM" src="https://user-images.githubusercontent.com/20116276/175537440-e9399720-9305-4ad1-bcbf-3da9351a301a.png">

**To Reproduce**
1. Go to https://teia.art/objkt/45586
2. Click on "Collect for 0.15 tez"
3. User is still allowed to collect from the "hen" banned account in "Listings"

**Expected behavior**
Listings for banned accounts should not be shown when they are the lowest swap. Using the example from above, the 1 tez listing should be shown instead of the 0.15 tez listing.

**Environment**
 - OS: Mac OSX
 - Browser Chrome
 - Version 103.x

**Comment by melMass** [comment]
Thanks for reporting!
I can look into it at the end of the day, @Theohorsmeier as it's kind of a follow up of #107 if you have time/will to check it before go ahead.

**Comment by spacegoodies** [comment]
@melMass Was this pushed to production? https://teia.art/objkt/45586

**Comment by melMass** [comment]
> @melMass Was this pushed to production? [teia.art/objkt/45586](https://teia.art/objkt/45586)

Hi space, it is in master, but the currently deployed site is still at an older commit (c5a3016f6d7a89d245f76f3ec583f9b06c786566)

It's not too obvious but I added it to the badges here to check what commit is deployed:
![image](https://user-images.githubusercontent.com/7041726/179027410-4d24ab8d-e008-4147-aa99-6f2da7a3254f.png)

Teia.rocks is 'always' synced with master though: 
https://teia.rocks/objkt/45586

Or this is the master staging link:
https://teia-ui-main.onrender.com/objkt/45586

Cheers
