### ISSUE TITLE
[feat] add a warning if no title is provided on mint

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#121]
currently it can happen that a user forgets to provide a title for an OBJKT in the minter
the title is then empty/null

while this can be intentional it might be useful to add a warning upon mint if a user hasnt provided a title

exaple:
https://teia.art/objkt/406272

**Comment by melMass** [comment]
It is indeed not a requirement, metadatas are in fact all optional. Only the file is mandatory. Not sure if we should enforce anything what do you think?

**Comment by merchantcoppola** [comment]
i wasnt thinking about forcing it, more like a warning text that comes up if a field is empty

i think its cool to have the option to leave the title blank ("untitled" is a very common thing, i feel like leaving out the name is actually an important feature) but maybe its good to get the warning (maybe, wasnt my request i just brought it here from a twitter space)

**Comment by melMass** [comment]
> i wasnt thinking about forcing it, more like a warning text that comes up if a field is empty
> 
> i think its cool to have the option to leave the title blank ("untitled" is a very common thing, i feel like leaving out the name is actually an important feature) but maybe its good to get the warning (maybe, wasnt my request i just brought it here from a twitter space)

I'm realizing now I slipped that in #113 we could do a new PR for it, but IMO the preview page is a clear indication if there is a title or not

**Comment by melMass** [comment]
Doing some cleanup, feel free to reopen
