### ISSUE TITLE
[feat] beacon modal is out of date

### ISSUE THREAD

**Issue by aebrer** [teia-community/teia-ui#124]
the beacon modal for logging in (syncing) is out of date

the latest version includes support for the new Temple mobile wallets

**Comment by aebrer** [comment]
sorry for the lazy formatting, in a rush :/

**Comment by melMass** [comment]
Thanks for the report, it's a bit harder than expected because of the way some sub-dependencies are packaged, *i.e. not as straightforward as just updating the deps*.
I'll take a closer look tomorrow

**Comment by aebrer** [comment]
thank you for looking into it :))

**Comment by aebrer** [comment]
I know this is closed, but it seems like the modal is still not up to date. There is no option to log in using Temple Wallet on mobile (which is currently the best mobile wallet IMO)

**Comment by melMass** [comment]
> I know this is closed

Yep sorry not super clear for now as we are addressing a bunch of issues lately.
This is solved in develop only for now (teia.rocks uses develop since 2 weeks)

It will soon land on main too

That's why we have the "solved in develop" tag :)

**Comment by aebrer** [comment]
ahh thank you for explaining I am too blind!

appreciate it :)))
