### ISSUE TITLE
[bug] unable to type numbers in the fields on the swap page

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#131]
On the swap page, you're able to type text, but no numbers.
I've rolled back commit a5b3c4f9c66b771dad74ec8145bc864609626ab8 on teia.rocks and that fixes it.
I'm not smart enough to debug this further.

![image](https://user-images.githubusercontent.com/546070/180277905-9cbe03db-ba25-4dcf-aebc-c3a05bef6078.png)
On the objkt quantity and price fields, only letters are accepted.

**Comment by melMass** [comment]
Thanks for the report!!

Fixed in #129 / #130

**Comment by Zir0h** [comment]
Doesn't work on https://teia-ui-main.onrender.com (and was also broken on my mirror, I put back the old fix from #132 )

// edit: only the quantity field is broken
