### ISSUE TITLE
about text update: tech specs

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#139]
### Describe the problem

we are missing tech info on our about page
for better transparency we should add info about the code and contracts
example: https://typed.art/about

### Describe the solution you'd like

The non-profit Teia Marketplace Interface and marketplace contract are [code forks](https://github.com/teia-community/teia-ui) based on the open source Tezos NFT marketplace [hic et nunc](https://github.com/hicetnunc2000) that have been and will be further developed and maintained  by the teia community.

Currently used Token FA2 (OBJKT) contract:  [KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton](https://tzstats.com/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton) 
developed and deployed by hicetnunclab2000 ([code on github](https://github.com/hicetnunc2000/objkt-swap))

Current Minting Contract:
[KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9](https://tzkt.io/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/operations/)
developed and deployed by hicetnunclab2000 ([code on github](https://github.com/hicetnunc2000/objkt-swap))

Adding this text below "report issues" (at the end of the current About page)

Teia Marketplace contract: 
[KT1PHubm9HtyQEJ4BBpMTVomq6mhbfNZ9z5w](https://tzkt.io/KT1PHubm9HtyQEJ4BBpMTVomq6mhbfNZ9z5w/operations/) 
forked from hicetnuncs marketplace contract and further developed and deployed by the Teia community ([code on github](https://github.com/teia-community/teia-smart-contracts/blob/main/python/contracts/teiaMarketplace_v1.py))
audited by [Inference AG](https://inference.ag/) ([audit report](https://github.com/InferenceAG/ReportPublications/blob/master/Inference%20AG%20-%20Teia%20community%20-%20marketplace%20%26%20multisig%20-%20v1.0.pdf)) 

Admin of the Teia marketplace contract: 
[KT1PKBTVmdxfgkFvSeNUQacYiEFsPBw16B4P](https://tzkt.io/KT1PKBTVmdxfgkFvSeNUQacYiEFsPBw16B4P/operations/) (community owned multisig). 
The [marketplace fees](https://github.com/teia-community/teia-docs/wiki/Marketplace-Fees) are temporarily set to 0%.
The [multisg contract code](https://github.com/teia-community/teia-smart-contracts/blob/main/python/contracts/multisigWallet_v1.py) was developed by Teia community and audited by [Inference AG](https://inference.ag/) ([audit report](https://github.com/InferenceAG/ReportPublications/blob/master/Inference%20AG%20-%20Teia%20community%20-%20marketplace%20%26%20multisig%20-%20v1.0.pdf)) 

All code and contracts above have been [released under the MIT license.](https://github.com/teia-community/teia-ui/blob/main/LICENSE)

### Alternatives considered

footer or menue could have this info but after a discussion on discord, the about page was considered best

**Comment by melMass** [comment]
Perfect thanks, I'll probably use a markdown component for the about, and remove the dependency on those half baked json language files.... We will deal with localization all at once IMO

**Comment by melMass** [comment]
## teia is ...

... a collaborative artwork made of artworks, a place for ideas and creative works.

... a non-profit, open-source online platform for trading digital assets as OBJKT NFTs.

... a collective, aligning under the values of sustainability, accessibility, and equity.

... owned and maintained by its community, built and improved by its participants.

---

Teia is and always will be a work-in-progress.

---

[**Core Value**](https://github.com/teia-community/teia-docs/wiki/Core-Values-Code-of-Conduct-Terms-and-Conditions#1-core-values) /
[**Code of Conduct**](https://github.com/teia-community/teia-docs/wiki/Core-Values-Code-of-Conduct-Terms-and-Conditions#2-code-of-conduct) /
[**Terms and Conditions**](https://github.com/teia-community/teia-docs/wiki/Core-Values-Code-of-Conduct-Terms-and-Conditions#3-terms-and-conditions---account-restrictions)

---

Find current news on our [**blog**](https://blog.teia.art), follow us on [**twitter**](https://twitter.com/TeiaCommunity), join the community on [**discord**](https://discord.com/invite/7pZrPCcgnG)

---

The wiki is available on [**Github**](https://github.com/teia-community/teia-docs/wiki)

---

[**Community Tools**](https://github.com/teia-community/teia-docs/wiki/Tools-made-by-the-community)

---

Report an [**issue**](https://github.com/teia-community/teia-ui/issues)

---

The non-profit Teia Marketplace Interface and marketplace contract are [**code forks**](https://github.com/teia-community/teia-ui) based on the open source Tezos NFT marketplace [**hic et nunc**](https://github.com/hicetnunc2000) that have been and will be further developed and maintained  by the teia community.

---

Currently used Token FA2 (OBJKT) contract:  [**KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton**](https://tzstats.com/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton)
developed and deployed by hicetnunclab2000 ([**code on github**](https://github.com/hicetnunc2000/objkt-swap))

---

Current Minting Contract:
[**KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9**](https://tzkt.io/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/operations/)
developed and deployed by hicetnunclab2000 ([**code on github**](https://github.com/hicetnunc2000/objkt-swap))

**Comment by merchantcoppola** [comment]
## Teia is ...

... a collaborative artwork made of artworks, a place for ideas and creative works.

... a non-profit, open-source online platform for trading digital assets as OBJKT NFTs.

... a collective, aligning under the values of sustainability, accessibility, and equity.

... owned and maintained by its community, built and improved by its participants.

... an infinite work in progress.

----------

[**Core Values**](https://github.com/teia-community/teia-docs/wiki/Core-Values-Code-of-Conduct-Terms-and-Conditions#1-core-values) /[**Code of Conduct**](https://github.com/teia-community/teia-docs/wiki/Core-Values-Code-of-Conduct-Terms-and-Conditions#2-code-of-conduct) /[**Terms and Conditions**](https://github.com/teia-community/teia-docs/wiki/Core-Values-Code-of-Conduct-Terms-and-Conditions#3-terms-and-conditions---account-restrictions)

[**Report an issue**](https://github.com/teia-community/teia-ui/issues)

----------

### Links

- News and articles: [**blog.teia.art**](https://blog.teia.art)
- Announcements and Updates: [**Twitter**](https://twitter.com/TeiaCommunity)
- Wiki: [**wiki.teia.art**](https://github.com/teia-community/teia-docs/wiki)
- Join the community: [**discord**](https://discord.com/invite/7pZrPCcgnG)
- Agora/Forum: **[discourse.teia.art](https://discourse.teia.art/)**
- Code: [**Teia Github**](https://github.com/teia-community)
- Community Curation: [**@TeiaArt**](https://twitter.com/TeiaCommunity)

----------

### Tech Specs

The Teia Marketplace Interface and marketplace contract are [**code forks**](https://github.com/teia-community/teia-ui) based on the open source Tezos NFT marketplace [**hic et nunc**](https://github.com/hicetnunc2000) that have been and will be further developed and maintained by the Teia community.

----------

**FA2 Token Contract:** [**KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton**](https://tzstats.com/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton)  - developed and deployed by [**hicetnunclab2000**](https://github.com/hicetnunc2000/objkt-swap)

----------

**Minting Contract:** [**KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9**](https://tzkt.io/KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9/operations/)  - developed and deployed by [**hicetnunclab2000**](https://github.com/hicetnunc2000/objkt-swap)

----------

**Marketplace Contract:** [**KT1PHubm9HtyQEJ4BBpMTVomq6mhbfNZ9z5w**](https://tzkt.io/KT1PHubm9HtyQEJ4BBpMTVomq6mhbfNZ9z5w/operations/) - developed and deployed by the [**Teia community**](https://github.com/teia-community/teia-smart-contracts/blob/main/python/contracts/teiaMarketplace_v1.py) and audited by [Inference AG](https://github.com/InferenceAG/ReportPublications/blob/master/Inference%20AG%20-%20Teia%20community%20-%20marketplace%20%26%20multisig%20-%20v1.0.pdf)

**Marketplace Contract Admin:** [**KT1PKBTVmdxfgkFvSeNUQacYiEFsPBw16B4P**](https://tzkt.io/KT1PKBTVmdxfgkFvSeNUQacYiEFsPBw16B4P/operations/) - community owned multisig

The [**marketplace fees**](https://github.com/teia-community/teia-docs/wiki/Marketplace-Fees) are temporarily set to 0%.  

----------
 
All code and contracts above have been [released under the MIT license.](https://github.com/teia-community/teia-ui/blob/main/LICENSE)

**Comment by melMass** [comment]
Follow up in #142
