### ISSUE TITLE
[bug] .md files can't be previewed for minting

### ISSUE THREAD

**Issue by LeonNicholls** [teia-community/teia-ui#149]
### Describe the bug

md files cannot be previewed

### Reproduction

Upload a .md text file for minting.
Press the preview button
Look at the browser console for an error.

![Screenshot from 2022-08-04 15-04-05](https://user-images.githubusercontent.com/564979/182933658-0822c25a-41b6-4308-8826-3d089d7efebd.png)

### Expected behavior

See md file contents on preview

### Platform and versions

```shell
Ubuntu
Google Chrome
```

**Comment by Zir0h** [comment]
This depends on the ipfs gateway. Works on a custom gateway: https://teia.rocks/objkt/765277

// edit, nevermind, I didn't see you were in the preview.

You can manually set the cid and it'll work :smile: 
https://cloudflare-ipfs.com/ipfs/QmZrs6t4MTuFu2YCXms4TntXNMc6cQhU5XPQ22v9ssGqQT

**Comment by NoRulesJustFeels** [comment]
Once the OBJKT was minted, I could view it fine. It was just the preview that didn't work.

**Comment by melMass** [comment]
Looks like this was never supported, I started adding it in aac2c2e6b358cea95971e9990ecf46ec6fe826dc

**Comment by melMass** [comment]
Solved as stated above so this issue will be closed when #146 is merged, but styling is wonky (as in "always was")
