### ISSUE TITLE
[feat] Use the nft.storage IPFS gateway

### ISSUE THREAD

**Issue by LeonNicholls** [teia-community/teia-ui#150]
### Describe the problem

Once we use the nft.storage IPFS service, we should consider using their IPFS gateway: https://nft.storage/docs/concepts/gateways/

### Describe the solution you'd like

Use https://nftstorage.link/ipfs/* for loading IPFS files

**Comment by Zir0h** [comment]
The only issue is the 200req/minute rate limiting:
https://nft.storage/docs/concepts/gateways/#rate-limits

It's quite easy to reach, you only have to scroll through your collection for example (I've tested this gateway on .rocks)

**Comment by melMass** [comment]
>  200req/minute 

Ouch, yes indeed, even if I think there is  a lot of room for optimization on our side to reduce the requests, 200/mn is prone to fails... 

I will add the option to switch to it without using it yet

**Comment by LeonNicholls** [comment]
We might want to ask nft.storage if they can increase the rate limit for requests from teia.art

**Comment by Zir0h** [comment]
Well, nft.storage doesn't really know where the requests are coming from I think.

We could self host it, there's a guide on their github:
https://github.com/nftstorage/nftstorage.link/blob/main/packages/edge-gateway/README.md
I think that's the only way to circumvent the ratelimiting.

**Comment by melMass** [comment]
AFAIK rate limiting is done per IP on the client side, I don't know the exact challenges/costs of self hosting a gateway, but IMO focus should be put on how to fetch less data (by fixing UI code), and how to better serve tokens (by using some CDN/Caching of cover and artifacts)

**Comment by LeonNicholls** [comment]
@dchoi27 is the edge gateway the only way to avoid the rate-limiting?

**Comment by dchoi27** [comment]
^ hm not sure if i understand - rate limits for the edge gateway as correctly stated above is 200 req / min. I'd advise not hosting your own gateway tbh - it's a lot of work.

One thing you might consider is using the SuperHot feature of https://nftstorage.link/ (scroll down a bit on the page) which can perma-cache the content you care about on the edge server. Then we could alleviate rate limits coming from teia.art (the rate limits are there to protect the underlying infrastructure we use to get data from the IPFS network, but if we know the data is already cached, it reduces concerns of exposing the underlying infra from being DDoS'd). 

if interested, I can get your NFT.Storage account access to the SuperHot API feature for you all to play around with! cc @vasco-santos

**Comment by Zir0h** [comment]
Even if we keep ipfs.io as gateway, general performance will improve greatly when we switch away from infura. It takes ages for files uploaded to infura to be available on the other gateways. Just today there was someone in the discord with this problem.

**Comment by xat** [comment]
we'll also soon be able to use the ipfs gateway provided by tezos commons. this gateway also supports thumbnail generation.

**Comment by xat** [comment]
although we'll need to put a caching proxy in front of that gateway.

**Comment by LeonNicholls** [comment]
Docs on superhot: https://www.notion.so/SuperHot-guide-ddf5a7def94b49ad9695209825b4ce1a

**Comment by melMass** [comment]
Closing as of #159  (we use NFT.storage for everything expect interactives).
