### ISSUE TITLE
[feat] Create a teia.art instance of the ipfs proxy

### ISSUE THREAD

**Issue by LeonNicholls** [teia-community/teia-ui#157]
### Describe the problem

Currently, teia.art is using https://ipfsproxy.teia.rocks/ as an IPFS proxy for nft.storage
Teia.art should have its own instance of the proxy

### Describe the solution you'd like

Host an instance of https://github.com/teia-community/ipfs-upload-proxy on the teia.art infrastructure

**Comment by LeonNicholls** [comment]
FYI. @jmagly

**Comment by jmagly** [comment]
thx for posting, this is on my to-do list, first focusing on pinning, for gateway there are some options. cloudflare for example now has a paid IPFS tier. 

owning the service is also possible

**Comment by Zir0h** [comment]
This is not for the gateway, this is for the upload of files to ipfs. Xat created this with the help of 852Kerfunkle so that we can hide our api key from the general public :)

This would also be helpful to enable the "superhot" caching system on nftstorage.link, because it relies on the api key.

**Comment by jmagly** [comment]
ahhh a pinning gateway,  do i need to find a place to run it or is that already figured and we just need DNS?

**Comment by Zir0h** [comment]
Currently it's running in a container next to the indexer. But I think it would be better to run that on teia infra too (with a teia api key from nft.storage + maybe some rate limiting?).

This is what I did:

Dockerfile
``` Dockerfile
FROM node:18-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app
RUN npm install 

CMD [ "npm", "run", "start" ]
```
docker-compose.yml
``` yaml
version: "3"
services:
  ipfsproxy:
    build: .
    environment:
      - API_TOKEN=theapikey(or with a .env file)
    restart: unless-stopped
```

**Comment by melMass** [comment]
@Zir0h this can be closed right? 😄

**Comment by Zir0h** [comment]
Yes, we can see later when we have some funds to install a dedicated instance of every service :smile: The upload proxy is using a bearer token that merch gave me, so it's already on a .art account.
