### ISSUE TITLE
[bug] there's a call to infura ipfs left in the config section

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#158]
### Describe the bug

It's impossible to update the Teia profile at the moment. People are unable to save and they're getting a 401 in the web dev console.

![image](https://user-images.githubusercontent.com/546070/184302749-f8877e70-209b-47a7-8e81-180ce442aa73.png)

Possibly because of this?
src/pages/config/index.js:const infuraUrl = 'https://ipfs.infura.io:5001'
src/pages/config/index.js:const ipfs = create(infuraUrl)

### Reproduction

1. go to your profile
2. make a change
3. save

### Expected behavior

Profile is updated

### Platform and versions

```shell
- Linux
- Firefox
- 103.0.2
```

**Comment by melMass** [comment]
I did not expect everything related to infura failing like that!
On it ;)
