### ISSUE TITLE
[feat] add local storage settings

### ISSUE THREAD

**Issue by melMass** [teia-community/teia-ui#189]
### Describe the problem

No user preferences.

### Describe the solution you'd like

While not ideal, for now using localStorage should still be better than nothing, here a few of the options we could have:

- [ ] IPFS Gateway (dropdown of popular gateways, with a `custom` option)
- [ ] Default Feed: a lot of people don't like last sales as the default feed.
- [x] Show Mature
- [x] Show Photosensitive
- [x] Custom Theme? (we could start with a color à la https://hen.miami/)
- [ ] Choose RPC nodes

### Alternatives considered

A proper encrypted backend

**Comment by LeonNicholls** [comment]
Some ideas: https://docs.google.com/document/d/1vYkB_BTwCQIzMPxQuX0EHrBCvjjxPJ-eZEtztN15mGI/edit?usp=sharing

**Comment by melMass** [comment]
UI/Style will be polished soon, but the base logic mentioned here is implemented, we can expand upon it with an issue / ideas 
![image](https://user-images.githubusercontent.com/7041726/216387785-84d530f6-d0d8-4637-8520-c3f662c87ac0.png)
