### ISSUE TITLE
[feat] make collab username clickable 

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#19]
on the signing status modal, it would be great if the usernames were clickable to go to that profile directly... would likely reduce confusion and risk of scams

(submittet by aebrer on discourse)

![collabclick](https://user-images.githubusercontent.com/97635650/158667122-fb29866f-2ec6-4091-a7fc-49c5b762b052.png)

**Comment by aebrer** [comment]
if whoever fixes this mints a screenshot of the MR or the "issue closed" page I'll put in an offer of 5 tez for it as a bounty
