### ISSUE TITLE
[bug] SVG links broken on overview pages

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#204]
### Describe the bug

For example on https://teia.art/makio135 a lot of the objkt links aren't working. 

### Reproduction

1. go to https://teia.art/makio135
2. hover over some of the objkts

### Expected behavior

mouse pointer should change to a little hand and you should be able to click on the objkt to see the details page

### Platform and versions

```shell
Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0
```

**Comment by melMass** [comment]
I don't see the bug on mobile,is this happening when clicking the SVG render preview or the OBJKT id <a> link?

**Comment by Zir0h** [comment]
It's on desktop, I can reproduce this on firefox and chromium. The objkt is shown, but the link just doesn't work.

The image on the left is broken, the one on the right works as expected.
![2022-10-08-134944_1187x1006_scrot](https://user-images.githubusercontent.com/546070/194706006-496313bf-689e-46ca-a5ff-ae4fc8660d3d.png)

**Comment by Zir0h** [comment]
I think the "interactive" part wins from the link?

**Comment by melMass** [comment]
Thanks!! I'll look into it later today 😀
