### ISSUE TITLE
[feat] Update to objkt.com v3 GraphQL API before January 30, 2023

### ISSUE THREAD

**Issue by LeonNicholls** [teia-community/teia-ui#208]
### Describe the problem

From objkt.com: "Earlier this month we released a new public API endpoint.

v2 will be shut down on January 30, 2023, roughly 3.5 months from now.

All public API users currently using https://data.objkt.com/v2/graphql will have to adapt their queries and migrate to https://data.objkt.com/v3/graphql before January 30, 2023.

To help with the migration here is an outline of the changes: [https://data.objkt.com/docs/changes-v3.html](https://objkt.us20.list-manage.com/track/click?u=f8c31dbd8f45266fc31a77856&id=c5a0855716&e=c9dd70cf13)"

### Describe the solution you'd like

Update to objkt.com v3 API

**Comment by melMass** [comment]
Afaik this will be handled by teztok anyway in our case in January. @xat

**Comment by xat** [comment]
yes, shouldn't affect us.
