### ISSUE TITLE
[bug] match style on the reswap field

### ISSUE THREAD

**Issue by melMass** [teia-community/teia-ui#21]
![image](https://user-images.githubusercontent.com/7041726/159120772-208e9186-1371-48d2-9707-5c8d89f60d74.png)

**Comment by scalemodal** [comment]
Added comment in PRs: https://github.com/teia-community/teia-ui/pull/20#issuecomment-1073014478
Here might more more right place for this.

**Comment by melMass** [comment]
Closing in favor of #22
