### ISSUE TITLE
[bug] The "editions" field in the minting page is croll sensitive

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#211]
### Describe the bug

The "Editions" field on the minting page is an integer field and thus "scrollable" - due to the minting page layout, if you fill out the editions last and scroll down to "upload objkt" it will reduce the edition size

we had this issue on other fields and it got fixed, it should get fixed here too

additional: it would be great to include "edition size" on the preview page so creators can check the edition size whe4n minting

![edition number](https://user-images.githubusercontent.com/97635650/201195892-e36c536e-e320-4681-bf7f-3ca0d64c5b07.JPG)
![scrollable](https://user-images.githubusercontent.com/97635650/201195897-a518b6d3-428b-4923-8798-2ce9b9f5fef5.JPG)

### Reproduction

1. go to https://teia.art/mint
2 fill out the form including a higher edition size
3. while the edition size field is still activated, scroll down to find the "upload objkt" butt

### Expected behavior

the edition field to not be sensitive to scrolling

### Platform and versions

```shell
windows, firefox explorer 
(but i am pretty sure it goes for all browsers)
```

**Comment by stumats** [comment]
Just confirming that its also an issue on Chrome desktop

I think the problem is that focus stays on that field until another field is clicked into. If focus is on that field and the mouse scroll is used, it not only scrolls but also changes an int field. Is the solution to change focus on the field after a timeout, or can the scroll behaviour be changed?

**Comment by melMass** [comment]
> Is the solution to change focus on the field after a timeout, or can the scroll behaviour be changed?

I think we will just disable scroll affecting fields all together, I think it can make sense for interactive controls with feedback but for fields on a form not so much
