### ISSUE TITLE
[feat] add ability to choose rpc nodes

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#212]
### Describe the problem

Currently the rpc node is hard coded in some places.
For example https://github.com/teia-community/teia-ui/blob/develop/src/context/HicetnuncContext.js#L46

### Describe the solution you'd like

It would be nice to be able to configure the rpc node endpoint in the .env file.

**Comment by Zir0h** [comment]
There's also this one: https://github.com/teia-community/teia-ui/blob/develop/src/context/HicetnuncContext.js#L909

**Comment by LeonNicholls** [comment]
It might also make sense to make the rpc node selection user configurable: https://docs.google.com/document/d/1vYkB_BTwCQIzMPxQuX0EHrBCvjjxPJ-eZEtztN15mGI/edit?mode=html#heading=h.8unfjcgegwi8
versum.xyz already allows users to change the rpc node.

**Comment by melMass** [comment]
> It might also make sense to make the rpc node selection user configurable

Check the commit 🥳

---

@Zir0h oopsie 😅 on it.

**Comment by melMass** [comment]
I'll close this but reference #189
