### ISSUE TITLE
[feat] Improve first-time user experience

### ISSUE THREAD

**Issue by LeonNicholls** [teia-community/teia-ui#217]
### Describe the problem

When a new user account is synced with the Teia UI, it is up to the user to figure out what to configure and how to use the site. This results in many new users never configuring their usernames or social profiles via tzprofiles. This also results in issues for collectors to verify the accounts' owner and creates complications for the content moderation team in verifying suspicious accounts.

### Describe the solution you'd like

Improve the initial user experience by providing recommendations and links to useful information about the community.

One possible new initial user experience could be to automatically redirect the new user to the config page: https://teia.art/config
That page could be redesigned to explain why each of the configurable fields is useful. This page could also display some useful information like how to use the fountain for their first mint and how to participate in the community.

**Comment by melMass** [comment]
Interesting, I think that it might be hard to properly detect "first" use, but one thing we could do, maybe as part of the local storage settings is to show a dismissible banner (dismiss is what would be stored in ls) for any address not registered as SUBJKT that points to the wiki.

**Comment by melMass** [comment]
I think this is now solved but we can open more specific issues if needed!
