### ISSUE TITLE
[feat] Add a "close" button to the main banner

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#219]
### Describe the problem

today http://teia.art/cyberhens requested a "close" option for the main banner on discord. i want to bring this issue here

the banner has been in constant use for month now. it is one one hand important for getting eyes on important news and events, on the other hand, if the banner stays live for so long, it might distract or worsen the UX. so a "close" button would solve this issue: users can just remove the banner 

### Describe the solution you'd like

a "close" button for the banner that would close the banner until a new banner is set up
![image](https://user-images.githubusercontent.com/97635650/205168802-d64fce23-30c3-4d51-85eb-ba536e404cd2.png)

### Alternatives considered

in the design suggestions by denscimonk the banner would be replaces by a more sophisticated "news bulletin" system and therefore this solution would be redundant

**Comment by melMass** [comment]
While I believe this will be replaced anyway in the new design. 
A solution could be to fetch the commit hash on https://github.com/teia-community/teia-status and use it as a key in localstorage

**Comment by melMass** [comment]
Yep, closing as this will be handled differently with blog/events soon.
