### ISSUE TITLE
[feat] overhaul UI fixes

### ISSUE THREAD

**Issue by scalemodal** [teia-community/teia-ui#22]
- [ ] **Standardizing content wrapper margins on mobile for all the pages .**  
Designed as 20px

On some pages margins are missing, because new design wasn't applied there yet.

Updated margins already:
https://teia.art/objkt/510549
https://teia.art/faq

Missing margins:
https://teia.art/
https://teia.art/about
https://teia.art/collaborate
https://teia.art/galleries/
https://teia.art/config
https://teia.art/dmt_vision (user profile tabs, manage assets)
https://teia.art/mint
https://teia.art/terms
https://teia.art/search

![image](https://user-images.githubusercontent.com/81647978/159121680-0c5313ce-82fd-4101-81e2-6c4807ec99d2.png)

- [ ] **Minimizing large distance/margin between content and header**
Especially on mobile
![image](https://user-images.githubusercontent.com/81647978/159121908-346b0bae-f6af-4bec-b2d0-7a55bea44578.png)
![image](https://user-images.githubusercontent.com/81647978/159121927-551cce4d-05b1-49ab-ae64-c964daa2fed5.png)

Please have a look suggested margins for the pages we are updating:
https://www.figma.com/file/R5sw1HcoHx4Aup1Yl7rGYA/UX%2FUI?node-id=1338%3A12652
Generally, you can find pink squares to check the sizes between the elements. 

- [ ] **Minimizing disclaimer - smaller font and shorter sentence**
Current disclaimer size is overlapping menu on smaller mobile devices.
Please apply font Small - 
![image](https://user-images.githubusercontent.com/81647978/159122169-189b0e7c-144b-4ef8-9c79-a1a04a6c414f.png)

![image](https://user-images.githubusercontent.com/81647978/159122381-ce475495-9570-4b00-b833-42840662fc67.png)

- [ ] **Updating disclaimer copy**
`This open-source, experimental dApp is developed and maintained by the Teia Community and powered by the Tezos blockchain.`

- [ ] **Updating menu intro copy**
`Teia is an artwork made of artworks, an open, community owned digital platform for experimentation, trading ideas and works of creativity as OBJKT NFTs.`

![image](https://user-images.githubusercontent.com/81647978/159122450-504e71ea-a667-4035-97b7-fac456e453d2.png)

- [ ] **Improving menu scrolling on mobile**
Currently I can't scroll the menu on iPhone - the content behind the menu is scrolling instead.
![image](https://user-images.githubusercontent.com/81647978/159122296-60131624-5a95-48d5-9068-03eeb12b0adb.png)

- [x] **Updating input fields and buttons on the reswap feature according to style**

![image](https://user-images.githubusercontent.com/81647978/159123830-04e9e39d-35af-4576-8343-b8daa4a82636.png)

Styles: https://www.figma.com/file/R5sw1HcoHx4Aup1Yl7rGYA/UX%2FUI?node-id=1406%3A11773

- [x] **Removing black background on the TEIA swap label.**
Transparent should be more suitable for light and dark modes.

![image](https://user-images.githubusercontent.com/81647978/159173278-044c1a41-17b2-428e-a6d6-65949c5c1892.png)

**Comment by merchantcoppola** [comment]
added the copytext updates to the copytext update collection issue: https://github.com/teia-community/teia-ui/issues/34

**Comment by melMass** [comment]
@denscimonk Can we open a new UI issue updated from the current version since a lot changed from that time?
if not I'll reopen 😄

**Comment by scalemodal** [comment]
> @denscimonk Can we open a new UI issue updated from the current version since a lot changed from that time? if not I'll reopen 😄

Some tasks are still actual, but yeah, I think I will create a new updated issue based on the current version.
