### ISSUE TITLE
[feat] add the SUBJKT name next to the wallet abbreviation when synced

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#222]
### Describe the problem

suggested via discord by root#3305:

### Describe the solution you'd like

 instead of the wallet abbreviation at the top we could show the username and avatar when applicable

### Alternatives considered

maybe instead of removeing the wallet abbreviation, the SUBJKT could be put next to the wallet address name
![nma](https://user-images.githubusercontent.com/97635650/206567462-7399e413-df13-434d-b0a0-317f84103b61.JPG)

### Additional context

maybe this is solved with new design updates for teztok integration?

**Comment by melMass** [comment]
@denscimonk thoughts?

**Comment by melMass** [comment]
![image](https://user-images.githubusercontent.com/7041726/216387323-241710f1-46b3-4971-af74-13cb67ad75a5.png)
