### ISSUE TITLE
[feat] trigger Zen mode/advanced info mode with hotkey (for the new UI)

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#230]
### Describe the problem

i personally like the info on the feeds but i really dont like them on the creations page/artist profiles - it feels to me like it affects the aesthetics of the artist creations page more than i thought, makes it look more like just another marketplace and less "soothing" - liked that very much about the hen artist profiles. so tuning it off and on easily would help imo.

![Uploading infozen.PNG…]()

### Describe the solution you'd like

i think having a hotkey switch for zen mode would be awesome - so users can quickly switch between the info and the zen mode
it would be important to add s![click z](https://user-images.githubusercontent.com/97635650/210888082-a5ff1e79-8e04-4ebe-880c-9c23e9649c49.PNG)me kind of description or alt text to the zen mode switch so people can learn how to use it

### Alternatives considered

turning the info stuff off on artists creations pages per default and allowing switching it on would also be an option but we would need to separate the modes for the global feeds and artist profiles and i think this would be confusing and cumbersome to implement.

### Additional context

see: mel-embx.onrender.com/

for me the info bars on artists profiles kinda mess with the "look and feel"/UX of the old teia UI: it makes it look more like trhe other marketplaces and more focused on commerce while taking away from the "gallery/art cenetered" feeling of the old grid

**Comment by merchantcoppola** [comment]
![infozen](https://user-images.githubusercontent.com/97635650/210890021-672907d8-8e5b-406b-b467-c86ad98d6680.PNG)

**Comment by melMass** [comment]
I personally think the Zen button is misplaced, but we could add shortcuts for feeds to switch the view & zen modes

**Comment by melMass** [comment]
This will be the Z key (works only on feeds because that's only where it's affected for now)
