### ISSUE TITLE
[bug] During Minting Audio File, Cover Image is not displayed in Preview

### ISSUE THREAD

**Issue by crcdng** [teia-community/teia-ui#234]
### Describe the bug

During minting an Audio File (wav) the UI does not display the uploaded cover image in Preview. Instead an error message is displayed.

### Reproduction

1. Mint
2. Upload Audio File
3. Upload Cover Image (jpg or png)
4. Click Preview

### Expected behavior

The uploaded Cover Image should be displayed in the preview. 

This is shown instead:

<img width="800" alt="Screenshot 2023-01-12 at 23 18 52" src="https://user-images.githubusercontent.com/830492/212195852-3c32cb3e-f86a-4ee4-a8cb-aab76e0549ed.png">

### Platform and versions

```shell
This was verified from 3 different computers with different file formats (jpg / png) during a workshop, at least one with MacOS and latest Chrome Browser (109.0.5414.87)
```

### Console output

```shell
Warning: single-file-hooks-frames.js:1 SingleFile is hooking the IntersectionObserver API to detect and load deferred images.
```

### Additional context

The NFT is minted correctly with the cover image (tested). Therefore the bug is in the Preview feature.

**Comment by Zir0h** [comment]
I get different behaviors. On preview.teia.art I get the `Metadata on queue` message, on teia.rocks I get the same message as the first post.

In the webdev console I see a call to `https://api.teia.rocks/v1/graphql`, it's as if it tries to fetch the token from the indexer and not from the previous form data.

```
query uriQuery($address: String!, $ids: [String!] = "") {
  token(order_by: {id: desc}, where: {artifact_uri: {_in: $ids}, creator_id: {_eq: $address}}) {
    id
    creator {
      address
      name
    }
    token_holders(where: {quantity: {_gt: "0"}}, order_by: {id: asc}) {
      holder {
        address
      }
    }
  }
}
```
