### ISSUE TITLE
[bug] out of memory crash when uploading a large mp4 on chrome

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#280]
### Describe the bug

When minting a large mp4, you're able to select the file, but after a couple of seconds the page crashes.
Smaller mp4's are working fine, the "upload cover button" never appears

### Reproduction

1 sync + go to the mint page
2 select a >1GB mp4 file
3 wait around 15seconds

### Expected behavior

The page should not crash

### Platform and versions

```shell
Chromium 111.0.5563.146 Arch Linux
```

### Console output

```shell
n/a
```

**Comment by melMass** [comment]
Thanks for logging it, yep it's a long lasting planned 'todo', for now I pass the whole file as bytes to the preview components 😅 .... This is pasted raw in the DOM and crashes.
The solution is to create an [object url](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL), it should be trivial:

**Comment by AlexandreRangel** [comment]
Bump : )
Hi Teia friends! Any news on this issue?

**Comment by melMass** [comment]
I will take a look in the weekend!

**Comment by AlexandreRangel** [comment]
Hi! Is the 1GB upload limit still on the plans?

**Comment by melMass** [comment]
> Hi! Is the 1GB upload limit still on the plans?

The limit is now more than that but the mechanism we use for previewing vidéo before mint creates OOM errors.
There are better approaches to do it and it's planned but no ETA yet, the issue is already elevated to high priority

**Comment by AlexandreRangel** [comment]
Great!! What's the current limit?

**Comment by Zir0h** [comment]
> Great!! What's the current limit?

2GB, been that way for a while now. It's only problematic if you run into this out of memory bug :sweat_smile:
