### ISSUE TITLE
[bug] line breaks are missing in the minting preview for the description

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#281]
### Describe the bug

when minting, the line breaks in the description text gets removed in PREVIEW which looks like the line breaks just get removed upon mint
however when proceeding to mint, the line breaks are working perfectly.

this lead to ppl afraid of minting bc the description looked weird in the preview

refernce objkt: https://teia.art/objkt/817511

preview:
![IMG_1546](https://user-images.githubusercontent.com/97635650/229314290-a06d9d16-f9ad-4e89-bbde-96d1063d8695.jpg)

mint:
![mint](https://user-images.githubusercontent.com/97635650/229314293-37dd025e-9969-48a1-aac4-59409fdce94e.JPG)

### Reproduction

mint an objkt with a line break and take a look at the preview

### Expected behavior

represent the line breaks correctly in the preview 

### Platform and versions

```shell
tested with firefox
```

**Comment by melMass** [comment]
Hmmmm that's a regression... I'll look into it thanks for logging it
