### ISSUE TITLE
[bug] Minting preview does not work for Interactive OBJKTs

### ISSUE THREAD

**Issue by ktorn** [teia-community/teia-ui#288]
### Describe the bug

When minting an Interactive OBJKT, the preview fails to render the piece.

It seems that the OBJKT is actually rendered and runs (for example, the piece can log to the console), but it is placed in an iframe of 0x0 dimensions.

I found that manually overriding the iframe's container with `width=100%, height=100%` temporarily fixes the preview.

![CleanShot 2023-04-07 at 02 30 07](https://user-images.githubusercontent.com/119677/230465017-34328379-1250-40b5-b029-047e02326fe1.png)

### Reproduction

1. Go to MINT
2. Fill in all the details as usual
3. Upload an Interactive zip file (HTML/JS) OBJKT (for this test I used one of the templates from Teia)
4. Hit "Submit" to proceed to the Preview

### Expected behavior

Expected the Interactive OBJKT to render on the Preview screen

### Platform and versions

```shell
Mac OS 13.2.1
Chrome 111.0.5563.146
```

**Comment by Zir0h** [comment]
should be fixed with https://github.com/teia-community/teia-ui/pull/354
