### ISSUE TITLE
[bug] 'Choose File' on Edit Profile does not work on first pass

### ISSUE THREAD

**Issue by Baloguna16** [teia-community/teia-ui#29]
**Describe the bug**
I went to my profile to change my picture. I clicked 'Chose File' to add a profile picture. The name of the file showed as expected, but without a preview of the profile picture. Thinking that I had added a profile picture, I selected 'Save Profile' which sent a transaction to my wallet. However, the transaction description said something like "operation failed". I cancelled the transaction and clicked 'Choose File' again, and *this time* the profile picture previewed.

However, I still get "Invalid Operation" in my wallet.

Screenshots: 
![IMG_1707](https://user-images.githubusercontent.com/25273046/159148562-95c4105f-63df-4b2b-aa3c-6f55a312582f.PNG)

<img width="1512" alt="Screen Shot 2022-03-20 at 12 43 45 AM" src="https://user-images.githubusercontent.com/25273046/159148578-31216520-666e-4682-9d7b-8cb63f880cb1.png">

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Profile'
3. Select 'Choose File'

**Expected behavior**
I should be able to add my profile picture (and complete the transaction necessary to save it). Then my profile picture change should be visible after the transaction goes through.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version 1.35.104

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.3.1
 - Wallet Galleon

**Comment by melMass** [comment]
Hi @Baloguna16 
 It seems like a combo of many different things, [Discord](https://discord.gg/fMuF5VvXAC) would be more appropriate to give you support on that, and we will create an issue accordingly if necessary.
 
 Thanks
