### ISSUE TITLE
[feat] Home feed configuration

### ISSUE THREAD

**Issue by melMass** [teia-community/teia-ui#301]
### Describe the problem

I want to choose the first feed I'm welcomed with on teia.art

### Describe the solution you'd like

Probably just added there as a local setting for now: 
https://teia.art/settings

### Alternatives considered

Whatever we might choose for a better option (IPNS was mentioned, "hijacking" the subjkt json etc...)

### Additional context

🫶

**Comment by caaatisgood** [comment]
hey @melMass could you help me understand the options of the first feed we're looking to let users choose? would love to help on this improvement!

**Comment by melMass** [comment]
Hey @caaatisgood thanks a lot for the proposal, that would be great.
It shouldn't be too hard. I wanted to wait my [huge PR](https://github.com/teia-community/teia-ui/pull/262) before addressing these but I don't think it makes much sense now and I'll have time soonish to address it properly.

For now let's go with option 1: use the browser local storage! Here are the rough steps, don't hesitate to ask questions:

1. We have this store here that uses `Zustand` and is automatically tied to local storage, so it should be a matter of adding the proper key for the type and the setter for the store (for instance `startFeed` or something like that):
https://github.com/teia-community/teia-ui/blob/e18769a602c9210af12859e17db14bb8152dbf90/src/context/localSettingsStore.ts#L68-L157 

2. Then to actually add an UI for it you can add a `Select` component in the `Settings.jsx` file (check the rpc line to see how to use it):
https://github.com/teia-community/teia-ui/blob/main/src/pages/config/Settings.jsx

3. Finally to actually use the setting's value as the actual start feed, you will need to edit this line:
https://github.com/teia-community/teia-ui/blob/e18769a602c9210af12859e17db14bb8152dbf90/src/index.jsx#L79 with the store value (you will probably need a map between `string` -> `feedComponent`, a bit like [this](https://github.com/teia-community/teia-ui/blob/e18769a602c9210af12859e17db14bb8152dbf90/src/components/header/feed_toolbar/FeedToolbar.jsx#L26-L48) but with the names as key and the component as value

**Comment by caaatisgood** [comment]
Hey @melMass thank you so much for the walkthrough. Very very useful! Just wanted to make sure that I understand the whole user flow and edge cases here.

## What we want to achieve

Give users the option to choose their preferred default feed (or `startFeed`). The list of options is [here](https://github.com/teia-community/teia-ui/blob/e18769a602c9210af12859e17db14bb8152dbf90/src/components/header/feed_toolbar/FeedToolbar.jsx#L26-L48).

## How we could achieve

Follow 1, 2 you mentioned above. And then, this is the main part I'd like to confirm, in `<RecentSalesFeed />`, we'd like to:
- Read the `startFeed` and redirect to it. ie if I chose `"New OBJKTs"` as my `startFeed`, I should be redirected to `/feed/newobjkts` when visiting the `/`.

If the above is the case. Then we'll also need to make sure the users are able to still navigate to `/` from the `startFeed` page. Essentially skipping the `startFeed` redirect in this particular case. The whole flow would look like this:
- The user starts a new session on Teia, starting from `/`
  - We check if the user has `startFeed` state, if
    - `truthy` -> redirect them to `startFeed` page
    - `falsy` -> do nothing (stays at `/`)
- (now let's assume that the user has `startFeed` "New OBJKTs") The user gets redirected to `/feed/newobjkts`
- Then the user clicks on the dropdown attempting to navigate back to `/`
- The user then gets redirected back to `/`
  - In this case, **the user should stay at `/` regardless of their `startFeed`**.

Okay if we're still on the same page til this point. I suggest that we keep a boolean state such as `hasVisitedRootPage` to make sure user stays on `/` if they are navigated from other feeds. The code on `/` would look something like this

```js
useEffect(() => {
  // note that states are all from `Zustand`
  if (hasVisitedRootPage) {
    return
  }
  // we set `hasVisitedRootPage` to `true` here
  if (!startFeed || startFeed === '/') {
    return
  }
  navigate(startFeed)
}, [/* ... */])
```

This would make sure that only the first `/` visit in a session will we check user's `startFeed` and redirect them to it. Afterward they could jump back on `/` or any other feeds freely without any `startFeed` checks.

LMK if it makes sense :)

**Comment by melMass** [comment]
Almost but I don't think redirection is a good idea, and it could be much simpler overall.

This line here: https://github.com/teia-community/teia-ui/blob/e18769a602c9210af12859e17db14bb8152dbf90/src/index.jsx#L79

Uses the `index` key of the react-router, that's where (in place of the current RecentSalesFeed- you will put the evaluated map value from the user settings (this is basically `/`), one thing that I did not think about in my previous message is that you will also need to make a proper route for RecentSales, but besides that there shouldn't be more steps

**Comment by caaatisgood** [comment]
ah right, utilizing the `index` key of `react-router` makes so much more sense. think i'm half way through it and will likely be submitting a pr in 1-3 days.

**Comment by caaatisgood** [comment]
Hey @melMass, apologies for the delay. Changes are nearly done. But I'm stuck on adding a commit with this `pretty-quick`-related error:
```sh
🔍  Finding changed files since git revision a43083cc.
/Users/xxxxx/.npm/_npx/15f9efe159c89f49/node_modules/pretty-quick/dist/isSupportedExtension.js:12
  ..._prettier.resolveConfig.sync(file, {
                             ^

TypeError: _prettier.resolveConfig.sync is not a function
    at /Users/xxxxx/.npm/_npx/15f9efe159c89f49/node_modules/pretty-quick/dist/isSupportedExtension.js:12:30
    at Array.filter (<anonymous>)
    at _default (/Users/xxxxx/.npm/_npx/15f9efe159c89f49/node_modules/pretty-quick/dist/index.js:53:157)
    at Object.<anonymous> (/Users/xxxxx/.npm/_npx/15f9efe159c89f49/node_modules/pretty-quick/bin/pretty-quick.js:17:27)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
husky - pre-commit hook exited with code 1 (error)
```
I've tried to install `eslint-plugin-prettier@^4.0.0` (following [this](https://stackoverflow.com/a/76697559/5876488)) but didn't work. Do you have an idea what might be the problem? I'm on Node.js v16.20.1 btw.

**Comment by caaatisgood** [comment]
quick demo on what i got so far

https://github.com/teia-community/teia-ui/assets/12913401/346f369d-907a-446b-92ad-05cb609aae9e

**Comment by melMass** [comment]
> Hey @melMass, apologies for the delay. Changes are nearly done. But I'm stuck on adding a commit with this pretty-quick

No pressure at all, take the time you need!
Yes it seems that Javier had the issue too on his end, I can't reproduce on either mac or windows, but I did find many issues about it, under the hood it just calls prettier, so I switched to `lint-staged`, you can apply the changes from here:
[`ee5711f` (#316)](https://github.com/teia-community/teia-ui/pull/316/commits/ee5711f47cfc2d83ffe70837bcf5c1a051899832)

We will then resolve the merge from you PR easily, but it should let you commit and format the code properly

**Comment by caaatisgood** [comment]
Thanks @melMass! It worked, just raised a PR https://github.com/teia-community/teia-ui/pull/325

**Comment by melMass** [comment]
And merged! Thanks again @caaatisgood
