### ISSUE TITLE
[bug] when changing your subjkt username, the field silently drops invalid characters

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#303]
### Describe the bug

When changing your subjkt username, the field silently drops invalid characters. This causes confusion with the end users. I think it might be better to block the form submit and show a warning. In that case the user can fix the username themself.

### Reproduction

1. go to https://teia.art/subjkt
2. insert a username what contains invalid characters (capital letters for example)
3. the invalid characters get dropped silently when unfocussing the field

### Expected behavior

The user gets a warning message with directions on how to fix their username

### Platform and versions

```shell
- Linux
- Firefox 113.0.2 (64-bit)
```

**Comment by melMass** [comment]
The kind of bug I hate as a user! I will look into it later today
