### ISSUE TITLE
[bug] The filetypes described in the minting form fopr cover images are incorrect

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#306]
### Describe the bug

when minting files that allow cover images (i.e. music in this example)
the minting form says it allows all kinds of files as cover images
but actuaqlly only images are allowed:

```
export const ALLOWED_COVER_MIMETYPES = [
  MIMETYPE.JPEG,
  MIMETYPE.PNG,
  MIMETYPE.GIF,
  MIMETYPE.MP4,
]
```

<img width="825" alt="Captura_de_pantalla_2023-06-21_a_las_10 03 20" src="https://github.com/teia-community/teia-ui/assets/97635650/0128203b-d6bf-4819-8c8a-3c969607be7d">

### Reproduction

mint audio file

### Expected behavior

either adjust the explainer text to reflect the file tyopes that are allowed, or allow more filtypes

### Platform and versions

```shell
n/a
```

**Comment by Zir0h** [comment]
Fixed with https://github.com/teia-community/teia-ui/pull/352
