### ISSUE TITLE
[docs] copy text updates for footer, swap info and about section

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#34]
# putting together the copy text updates we got so far

## Updating disclaimer/footer copy:

(crzy asked us multiple time to get rid of his name on the site, so this one has the highest prio out of the copytext updates)

replace this:
![footer](https://user-images.githubusercontent.com/97635650/159556378-06db92d6-3d56-4ab1-ad34-c3ad2a30d90c.JPG)

- [x] with this:

`This open-source, experimental dApp is developed and maintained by the Teia Community and powered by the Tezos blockchain.`

---

## Updating menu intro copy:

replace this:
![disclaimer](https://user-images.githubusercontent.com/97635650/159556050-ed0bc1f2-31b0-4aaa-a80e-d028e359968a.JPG)

- [x]  with this
`Teia is an artwork made of artworks, an open, community owned digital platform for experimentation, trading ideas and works of creativity as OBJKT NFTs.`

---

## Updating swapping info copy text:

replace this: 
![swappinginfo](https://user-images.githubusercontent.com/97635650/159556676-39d63c07-0f0b-4be2-b03f-7dd36075658f.JPG)

- [x] with this:

`The Teia marketplace fee is temporarily set to 0%. Please consider donating to the address hereandnow-fund.tez for maintenance funding.`

----
## Updating "about" page copy text

replace this:
![aboutcopy](https://user-images.githubusercontent.com/97635650/159556965-18a716a6-2980-487d-b3f4-2fcdd685316f.JPG)

- [x] with this:

```
<headline> Teia is ....

... a collaborative artwork made of artworks, a place for ideas and creative works.
... a non-profit, open-source online platform for trading digital assets as OBJKT NFTs.
... a collective, aligning under the values of sustainability, accessibility, and equity.
... owned and maintained by its community, built and improved by its digital citizens.

Teia is and always will be a work-in-progress.

<link> Core Values / Code of Conduct / Terms and Conditions

```

**Comment by melMass** [comment]
Nice, edits are on going at [this url](https://teia-ui-pr-35.onrender.com/), only the `about` remains ;)
