### ISSUE TITLE
[feat] 404 page

### ISSUE THREAD

**Issue by xat** [teia-community/teia-ui#38]
as discussed in discord, it would be good to have a 404 page. maybe a designer can come up with a nice TEIA-404 image.

this will also require some refactoring of the routing logic.

**Comment by melMass** [comment]
This will probably be tackled as part of the routing refactoring.

**Comment by melMass** [comment]
Might still need some design later on cc @denscimonk but this is solved in 0aac834e9e39a93179a423bbe5d8c93ce4a8c4b9
(some edge cases might not yet be supported)
![image](https://user-images.githubusercontent.com/7041726/216372817-0679bc6a-2410-4726-a2f2-68981089c0e3.png)
![image](https://user-images.githubusercontent.com/7041726/216372907-7688d6ea-2890-43d6-bc0f-aae7267e0545.png)
![image](https://user-images.githubusercontent.com/7041726/216372938-434279af-3709-477b-9b41-55027ad16032.png)
