### ISSUE TITLE
[feat] / bug? swapped objkts dissapear from collection

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#387]
### Describe the problem

I just noticed that when you list a piece that you have collected to swap, it sort of disappears from your collections page.  I wasn't expecting that.  I'd kind of like to see it there in my collections page still unless someone else buys it.  I guess because it's put onto the Teia marketplace address then it doesn't appear on your collections page anymore?  I wonder if there is way you can see all the items you have collected and are reselling on a page?

-floydwilde on discord

### Describe the solution you'd like

Objects stay visible in collection

### Alternatives considered

Maybe a page with all swapped objects for your wallet?

**Comment by floydwilde** [comment]
Might be better to wait until #383 is closed to look at this more.

**Comment by Zir0h** [comment]
Fixed with https://github.com/teia-community/teia-ui/pull/388
