### ISSUE TITLE
Files loading into wrong ends.

### ISSUE THREAD

**Issue by garubim** [teia-community/teia-ui#394]
### Describe the bug

I minted a video piece today, a complex one. What loaded was a 12 frame gif that I uploaded as cover where the cover was supposed to be uploaded and a, audio control bar under the gif to play only the music of the piece I uploaded. I can only conclude it is a bug. I tried getting help on Teia's discord without any success. I hope this issue gets solved soon. 
There's one more issue. I clicked on the "view on ipfs" button to check if the file was uploaded right and a popup download window came up for me to chose the download destination. I believe this is not a default for seeing the filles on ipfs, right?

### Reproduction

1,
2, 
3 

### Expected behavior

I described all above

### Platform and versions

```shell
IDK
```

### Console output

```shell
IDK
```

### Additional context

I've minted many video works on Teia and HEN without any of the issues I mantione above.

**Comment by garubim** [comment]
I burned the piece  but it can be seen at it's original url:
https://teia.art/objkt/848306/burn

**Comment by melMass** [comment]
This looks like a codec/format issue, did you manage to mint it in the end?

**Comment by garubim** [comment]
> This looks like a codec/format issue, did you manage to mint it in the end?

Yes I did, the team answered me on Discord. Thank you!

**Comment by garubim** [comment]
> This looks like a codec/format issue, did you manage to mint it in the end?

All solved, tyvm! 
https://teia.art/objkt/848339
