### ISSUE TITLE
[feat] Add Farcaster Frame Tags

### ISSUE THREAD

**Issue by kylegrover** [teia-community/teia-ui#398]
### Describe the problem

Support for advanced Farcaster/Warpcast embeds

### Describe the solution you'd like

Looks as easy as adding opengraph style tags

example: https://replit.com/@soren/Linktree-Frame?v=1#index.js
docs: https://docs.farcaster.xyz/learn/what-is-farcaster/frames

### Additional context

Inspired by this poll + preliminary results: https://teia.art/poll/18

**Comment by Zir0h** [comment]
implemented via #400
