### ISSUE TITLE
[feat] standard way to display errors

### ISSUE THREAD

**Issue by xat** [teia-community/teia-ui#4]
it would be nice to have some general way to handle errors. currently, errors are often not handled and the ui just becomes black or white.

what we need is a standard way to display errors (for example with some growl-like library). some errors could also be captured by using reacts error boundaries.

**Comment by melMass** [comment]
### Place I can think of:

- [x] Username already taken as suggested in ( teia-community/teia#5 )
- [x] Mint failing (on that note mint success also ends up in a "dead space"
- [x] Trying to buy a piece that is no longer available.
- [x] Kind of related also, when going to an unknown route `/tz/teteteia` returns `/tz/`

This might actually be a milestone

**Comment by melMass** [comment]
All the points mentioned here are solved in 0aac834e9e39a93179a423bbe5d8c93ce4a8c4b9
