### ISSUE TITLE
[bug] validation of the minting form is bugged

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#430]
### Describe the bug

Multiple reports on the discord that the minting form is bugged

### Platform and versions

```shell
n/a
```

**Comment by Zir0h** [comment]
Possibly related to the copyright adaptations from the previous PRs

**Comment by kylegrover** [comment]
some complaints about losing form data as well, maybe we can throw that in local storage and autofill or provide a 'refill recent' button

**Comment by Zir0h** [comment]
Should be fixed with https://github.com/teia-community/teia-ui/pull/431
