### ISSUE TITLE
[bug] shares calculation for Beneficiaries is broken?

### ISSUE THREAD

**Issue by Synkitten** [teia-community/teia-ui#51]
*Please fill out the following Bug Report Template

**Describe the bug**
Testing collab contract function on https://teia-ui-main-pr-25.onrender.com/collaborate
No issues until trying to add a beneficiary manually - 
The automatic shift of the Collaborators percentages worked well when I added any of the popular beneficiaries in the drop down menu -  I put the initial shares of the collaborators at 50 each and then decided to test the beneficiaries and selecting the 5% adjusted the other two correctly. 
Ok once I manually deleted the [object object] words in the text box it allowed me to paste in a wallet address but behaved a bit oddly so not sure if it needed a refresh.
Ok I repeated twice, if I tried to paste the address from clipboard into the space without deleting the words [object object] manually nothing will paste into the area and it will delete the information from clipboard (checked clipboard and attempted to paste in other areas without success) but if I recopied the address and deleted the words first it pastes in just fine.  (edited)

But then the percentages don't adjust properly and the next screen added up to 104%
Also a second 'Next' button turned up while it was just sitting on the screen without interacting, you can see it in - <img width="765" alt="2 buttons" src="https://user-images.githubusercontent.com/94412910/161011813-b7c34594-294e-4ade-9e4c-b6bbe8b07ce5.png">

**Screenshots**

<img width="686" alt="add up" src="https://user-images.githubusercontent.com/94412910/161011819-ad9593f1-466b-4b04-8498-f70b927c58bf.png">
<img width="690" alt="collaborate and beneficiaries" src="https://user-images.githubusercontent.com/94412910/161011823-c8513672-142d-4c83-b2fa-e5d40dbf760e.png">
<img width="763" alt="manual enter beneficiary" src="https://user-images.githubusercontent.com/94412910/161011827-5fd95446-4ee9-40af-a195-a4c62eb4bc4f.png">
<img width="962" alt="1" src="https://user-images.githubusercontent.com/94412910/161011829-7d5aca49-de9e-47d6-9d6c-69813fd55ed3.png">

**Desktop (please complete the following information):**
 - OS: [PC Windows 10,64 bit]
 - Browser [Brave]
 - Version [1.36.122]

**Smartphone (please complete the following information):** I haven't tested on phone yet

**Additional context**
Beneficiary wallet - tz2LYfLnMbAY21GCkRHnPrNWLu6oz8dbeCCV
I got the address from Giving Block

**Comment by melMass** [comment]
From the top of my head everything stated here is fixed in master (and deployed to teia.art), besides the beneficiary calculation if you input another value than the one proposed in the buttons (5%,10% etc...).

**Comment by melMass** [comment]
Renamed to nail it to the only remaining issue filed here.

**Comment by melMass** [comment]
Solved, but can't really track where 😅
