### ISSUE TITLE
[null] Add a != tag filter option for the main feed

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#58]
bringing this request from discord/notion here:
during the launch people where asking to filter out the tag "spider" bc of arachnophobia
a != filter could help people to avoid certain topics/images

**Comment by melMass** [comment]
How would that work? Especially UX wise, is it a field where you list all the "forbidden" words/tags, if we have to check every descriptions / title / tags it might get a bit heavy. Poking @xat if he has a better approach

**Comment by melMass** [comment]
Closing for now, we can re-open if needed
