### ISSUE TITLE
[feat] show collab objkts under "Creations" tab of the core collaborator IF there is only one core collaborator, and the work is signed 

### ISSUE THREAD

**Issue by aebrer** [teia-community/teia-ui#60]
Currently, it's possible to create a collab contract where you are the only core collaborator, with others as beneficiaries. This is a powerful way to use Teia for: 

- automatic donations to charity (eg. Ukraine)
- automatic donations to Breadfond
- automatic payments to a service (like conjure, where I send 20% of what I make from art I made with their tool)
- having a nice contract based collection of art that can be viewed in one place

an example of a collab setup like this can be seen here: https://teia.art/collab/ideocartography_realized_retired_20220711 
[EDIT: updated link]

Given that the art in this type of "collab" contract really does only have one creator, I believe that it makes sense to list these under the "Creations" tab of that core collaborator, rather than the "Collabs" tab. I also hope (but don't know for sure) that this could also improve discoverability for these pieces.

**Comment by littlecakes** [comment]
i would really like this feature as well!
