### ISSUE TITLE
[bug] Clicking "new OBJKTs" gives an error in web developer console

### ISSUE THREAD

**Issue by Zir0h** [teia-community/teia-ui#61]
**Describe the bug**
If you click on the "new OBJKTs" menu item, a POST call is sent to graphql with the wrong parameters(?) In the web developer console (and in the indexer db logs) you can see the following message:
`{"errors":[{"extensions":{"path":"$","code":"data-exception"},"message":"invalid input syntax for type bigint: \"Infinity\""}]}`
In my testing the issue only appears the first page load. If I hit F5 and try again, it works.

Is it possible that the $lastId [here](https://github.com/teia-community/teia-ui/blob/dad0bd0d2a1bff7dc08a06bf5bd064d04060a353/src/pages/feeds/feeds.js#L35) jumps from 99999999 to Infinity?

**To Reproduce**
1. Go to https://teia.art
2. Click on 'new OBJKTs'
3. Notice the the page stays empty.
4. See error in web developer console

**Expected behavior**
Clicking the 'new OBJKTs' link fills the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/546070/162291302-2bfbbb16-d830-4c96-b93c-191d4f7d1f66.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: firefox
 - Version: 98.0.2 (64-bit)

Also reproducible in Chromium Version 99.0.4844.84 (Official Build) Arch Linux (64-bit)

**Comment by melMass** [comment]
I cannot reproduce that, but the return value used is wrong apparently `new objkts` gives me:
![image](https://user-images.githubusercontent.com/7041726/162334100-6d5dc484-34f2-4e3a-a9f0-829629214852.png)

I'm going to look into it but I think I know how it happened.
