### ISSUE TITLE
[bug] "reswap" button not working on mobile

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#65]
I am bringing this issue here from malicious sheep who reported it in discord
i am not able to test it since i dont use teia on mobile

they said:
"""
I just attempted and the reswap button isnt working on mobile. It indicates it was selected by slight colour change, but it didn't engage the wallet or indicate anything at the top of browser. 
"""""

**Comment by melMass** [comment]
Can anyone confirm? I just tested it works fine

**Comment by melMass** [comment]
Closing as I'm cleaning issues a bit and we need more infos, don't hesitate to reopen
