### ISSUE TITLE
[feat] show burn action in history? (+bug)

### ISSUE THREAD

**Issue by stumats** [teia-community/teia-ui#69]
**Describe the bug**
Seems that in the new UI, history doesn't show burns.
This then appears to cause swap numbers to vary, and the initial mint seems to be incorrect.

**To Reproduce**  EXAMPLE
1. Go to '...'  [715249](https://teia.art/objkt/715249) 
2. Click on history

4. See issue-   it says minted 10 / swapped 20

**Expected behaviour**
I'm assuming that 20 were minted, 20 were swapped and then 10 were burnt.
expect to see either that 10 were burned (and initial mint was 20) , or minted 10 / swapped 10 (if none were burned)

This is the only example I have evidence for, but have noticed inconsistencies in History listings before, that seem to imply burning may have happened.

**Comment by Zir0h** [comment]
Do we need an indexer update for this? In [on_transfer](https://github.com/teia-community/hicdex/blob/d0b0830bf630f3e77241442b609b0821377ee2ee/src/hicdex/handlers/on_transfer.py#L8) the only thing we keep is the amount of objects that get burned/transferred, no timestamp or ophash.

Correct me if I'm wrong but I think at the moment we can only show the total amount of burned tokens?

**Comment by melMass** [comment]
> Correct me if I'm wrong but I think at the moment we can only show the total amount of burned tokens?

I don't know how it's stored in the indexer but we could always use tzkt for these only

**Comment by Zir0h** [comment]
Something like this maybe?

https://api.tzkt.io/v1/operations/transactions?target=KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton&parameter.[*].txs.[*].token_id=721834&parameter.[*].txs.[*].to_=tz1burnburnburnburnburnburnburjAYjjX&level.gte=2308178&entrypoint=transfer&status=applied

**Comment by stumats** [comment]
maybe... not sure what that looks like in practise :-)    Can you bring in date too? (oh - date is there already I think)
