### ISSUE TITLE
[feat] PDFs dont get rescaled on desktop pc

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#72]
I minted a (squared) pdf yesterday and it looks like PDF files on objkt pages dont get rescaled like other file types are
on my first try the PDF was too big so it wouldnt fit into the browser window

this is the corrected version, where i sacled to 1000px in my layout program (https://teia.art/objkt/717662)

i think it would be nice to have the pdfs autoscaled on the objktpages

**Comment by encapsuled** [comment]
Before PR:

<img width="1440" alt="Screen Shot 2022-04-14 at 11 26 28" src="https://user-images.githubusercontent.com/102979725/163356183-cf2121a0-87e0-4e72-8cd3-1e3509327a89.png">

After PR:

<img width="1440" alt="Screen Shot 2022-04-14 at 11 43 59" src="https://user-images.githubusercontent.com/102979725/163359303-d82949a9-e099-4db8-8972-569edc2a71c8.png">

PR link: 
https://github.com/encapsuled/teia-ui/pull/1
