### ISSUE TITLE
[feat] hicetdono integration (resolve contract address + claim)

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#84]
While answering questions about giveaway options i thought that it would be really cool to better show on the TEIA UI if editions are up for free on hicetdono. (https://dono.xtz.tools/)
![dono](https://user-images.githubusercontent.com/97635650/166139066-c7237e56-25d4-4941-b0ab-e504132cc645.JPG)

can we give the hicetdono contract (KT1GziMhWS28ywwCXT4BJxpN6CkF6jqcUiWi) the name "on dono.xtz.tools" or something similar?

or even better: since we integrated objkt and hen swaps, can we make the giveaway claim from hicetdonos smartcontract available trough the teia UI? (like the other marketplace contracts)? if that was the case, hicetdono could become the best way to put up giveaways that are limited to 1 edition per wallet.

**Comment by aebrer** [comment]
this would be really awesome, and would really help a ton with giveaways and community events on Teia

**Comment by melMass** [comment]
Do you have an example of 

>  can we make the giveaway claim from hicetdonos smartcontract available trough the teia UI? 

I'm not sure to understand

**Comment by merchantcoppola** [comment]
> I'm not sure to understand

https://dono.xtz.tools/
now uses a smartcontract for making claims available. you click "i want in" on dono and you get one edition sent.
it works a bit like a marketplace contract but every wallet can only get 1 edition
if we integrated that hicetdono claims like we did with objktcom swaps it would make giveaways available and visible on teia which would help with giveaways, currently you can only claim them on dono and a lot of people are not aware of that.

**Comment by melMass** [comment]
Nice, I'll look into it as I'm not familiar with it and last time I used dono you had to reserve in advance and the token was sent on a given date, I guess it changed

**Comment by melMass** [comment]
Ok now should be a good time to look into this, @PureSpider can I contact you on discord for the integration?
