### ISSUE TITLE
[feat] update donation address in swap tab to new main donation address

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#89]
since the donation setup changed a bit and we got a new donation .tez address, could we quickly change that in the swap tab alt text?
![address](https://user-images.githubusercontent.com/97635650/169690628-9f16b1c0-d058-4a61-9a98-2d1ecfa8afee.JPG)

the new address is:

teiaescrow.tez (tz1Q7fCeswrECCZthfzx2joqkoTdyin8DDg8)

would be cool to bring that in line, thanks!

**Comment by merchantcoppola** [comment]
mel this was another issue, not the added addresses in the collab contract suggested beneficiaries

**Comment by merchantcoppola** [comment]
created a PR for this too:
https://github.com/teia-community/teia-ui/pull/96

**Comment by melMass** [comment]
> mel this was another issue, not the added addresses in the collab contract suggested beneficiaries

I don't understand?
https://github.com/teia-community/teia-ui/pull/90/files
