### ISSUE TITLE
[feat] add a "restricted" tag to restricted addresses on the "listings" tab

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-ui#93]
swaps from restricted accounts are not executable through teias UI
but it is currently unclear to the user why a swap is displayed without a price
i suggest adding a "restricted " tag to either the swap (instead of the contract info that is currently displayed like H=N, Teia, Objktcom)

or - imo even better - mark an restructed account as restricted right next to the address/SUBJKT to warn people 

or - if we want to stay minimalist - make the address name darker than the nor restricted ones

![save](https://user-images.githubusercontent.com/97635650/170574095-f6bddc44-5412-47a6-bbc3-bc527e6f9c98.JPG)

**Comment by Theohorsmeier** [comment]
On top of showing a Restricted label, I noticed that Objkt.com listings were not hidden like Teia/HeN swaps are in case of a banned account, so I added that check too.
