### ISSUE TITLE
[support] 504 Gateway Time-out

### ISSUE THREAD

**Issue by antoineschmitt** [teia-community/teia-ui#94]
Hello,
the page of my artwork does not display the artwork. Instead, it displays a "504 Gateway Time-out" error. The text is OK, only the artwork does not display. 

The link : https://teia.art/objkt/726132

The artwork is an html site with javascript. It is quite small in size. It was working when I posted it a few months ago. This has been like this for a few days/weeks. All my other artworks, including others html/javascript, work fine.

Before the error appears, the status line says "Waiting for data.objkt.com...", and sometimes "Waiting for ipfs.io..."

This is Mac/Brave. No adblocks.

Thanks !

**Comment by antoineschmitt** [comment]
I wonder if this is because the artwork supports Ukraine. I've heard that some people have had problems with artworks supporting Ukraine...
Any help ?

**Comment by Zir0h** [comment]
This is more a problem with the ipfs gateway. http/504 is when the webserver gives up on waiting for the reponse from the backend. In this case ipfs.io aborts its connection to the ipfs backend after 5 minutes I think?

Nothing to do with the Ukraine artworks, they might just be bigger in size or they were last fetched a long time ago.
That's just the way ipfs works I'm afraid.

You can try to to open the ipfs link on another gateway to refresh the cache, in your case the ipfs link is:
https://ipfs.io/ipfs/Qmbs5iqJJ2xBxZFWht33JHQAQ329zpX922Pw8bPmiv3qmb
if you open that link, but change the hostname to cf-ipfs.com, you open via the cloudflare ipfs gateway and that helps the ipfs.io gateway.
So: https://cf-ipfs.com/ipfs/Qmbs5iqJJ2xBxZFWht33JHQAQ329zpX922Pw8bPmiv3qmb

Another thing that helps is [pinning your artworks](https://github.com/teia-community/teia-docs/wiki/IPFS-pinning)

**Comment by antoineschmitt** [comment]
Thanks so much !
The file is really small (less than 40Kb), but I guess that it was just long to retrieve from ipfs.
Refreshing the ipfs cache with the cf-ipfs.com did the trick, and it now appears fast in ipfs.io and teia.
I also pinned it using pinata, so that will probably help in the future.
Thanks for the help !

**Comment by melMass** [comment]
Thanks @Zir0h !

I also noticed that there is always a delay after the initial IPFS upload before it's properly available around the world consistently.
Pinning is always recommended on top of that. I'll close the issue, don't hesitate to open a new one if needed
